Fix NoSuchMethodError in commons-io (#2587)
* add diagnostics per #2509

* ConnectionFactory: Catch all LinkageErrors, not just NSME.

* Avoid use of IOUtils because of 1.4(Gradle) vs 2.6(Application) incompatibilities causing NSME. Fixes https://github.com/jeremylong/DependencyCheck/issues/2509

Co-authored-by: Jeremy Long <jeremy.long@gmail.com>